### ISSUE TITLE
Organization should be more general

### ISSUE THREAD

**Issue by schemar** [OpenSTFoundation/openst-protocol#543]
The organization and its related contracts should be identical in the `openst` and the `mosaic` repository. For that we need a generalized organization.

## Todos

- [x] Organized modifiers
- [x] Restructure organization interface
- [x] Make admin internal and give it all rights of owner
- [x] Delete `OpsManaged` and `Workers`
- [x] Replace `isOwner` with `isOrganization`
- [x] Remove assignment restrictions (documentation!)
- [x] Remove `Owned`
- [x] Initialize on construction

## Organization

The organization should no longer leak the internals of an admin. From the outside (interface), it should only have the notion of "the organization" and "workers of the organization".
The admin in the organization is an implementation detail of this implementation of the organization where the owner can delegate all rights to an appointed admin.
This means that the `isOwner` method should instead be called `isOrganization`. It should return true for both cases where `msg.sender` is the owner and where `msg.sender` is the admin. The owner grants the admin all rights on the owner's behalf.

### Restrictions

Remove any existing restrictions that restrict a role to be assigned or not assigned to specific keys. For example, it should not be forbidden for the owner to be the same key as the admin.
However, in the documentation it should be made **very** clear that that is not a good idea in practice and that it is always a good idea to use different keys for owner, admin, and workers. 

### Interfaces

Remove the `OrganizationInterface`, which is not used anywhere, and instead make the `IsMemberInterface` the `OrganizationInterface` with the methods `isWorker` and `isOrganization`.

### Initialization

When constructing the organization contract, it should be possible to initialize it with a given owner, a given admin, an array of workers, and their expiration height. Only a single expiration height for all workers.

## Organized

Organized should have the modifiers `onlyWorker` and `onlyOrganization`. The organization implementation should not leak the fact that it can set an admin to act on behalf of the organization.

## ℹ️ Info
Once the organization is updated, a PR should be opened on [openst-contracts](https://github.com/OpenSTFoundation/openst-contracts) to apply the changes there as well

**Comment by schemar** [comment]
This ticket is up for discussion and there are open questions. E.g.

* Do we need more modifiers (e.g. `onlyOwnerOrAdmin`)?
* Do the interface changes make sense?

Discussion will happen next week on Monday.

/cc @abhayks1 @jasonklein @pgev
